
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

import java.awt.Container;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import javax.swing.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JRViewer;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 * 
 * 
 */

//Connection conn=null;
//   // ConItem cn1;
//   mysql2 obj=new mysql2();
        
 
//    public Internalitemreport() {
//        initComponents();
        //conn=obj.connect();
public class Configreport extends javax.swing.JInternalFrame {

    /**
     * Creates new form Configreport
     * 
     * 
     */
    
    Connection conn=null;
   // ConItem cn1;
   mysql2 obj=new mysql2();
    public Configreport() {
        initComponents();
         conn=obj.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Config report");

        jButton1.setText("View All Config");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("view particular staff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(52, 52, 52)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
            //cn1=new ConItem();
                //JasperDesign  jasperDesign=JRXmlLoader.load("report4.jrxml");
           //JasperDesign  jasperDesign=JRXmlLoader.load("Itemreport.jrxml");
         //    JasperDesign  jasperDesign=JRXmlLoader.load("config.jrxml"); 
              JasperDesign  jasperDesign=JRXmlLoader.load("report/config.jrxml");
           // String sql="select * from rani";
          //  String sql="select  type,item_name,item_type,price,Quantity from item2";
     // String sql=      "SELECT c_type, basicsalary ,hourlysalary, ha, ta ,pf ,esic from config" ;
String sql=     " select c_type,basicsalary ,hourlysalary,ha,ta,pf,esic from config where status='Áctive'";
//"     esic
//
//     c_type,
//     basicsalary ,
//     hourlysalary,
//     ha,
//     ta ,
//     pf ,
//     esic
//FROM
//      config";
            JRDesignQuery  newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, null,conn);
//            JasperViewer.viewReport(jasperprint);
//             JasperViewer.viewReport(jasperprint,false);
            JasperViewer.viewReport(jasperprint, isClosed);
         
         
         
           
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          try
        {
            //cn1=new ConItem();
           // String filename="reportItem.jrxml";
             String filename="itemtype.jrxml";
             String s= jTextField1.getText();
          //  String veg="veg";
             //   JasperDesign  jasperDesign=JRXmlLoader.load("lib/reportItem.jrxml");
               //  JasperDesign  jasperDesign=JRXmlLoader.load("configpara.jrxml");
                  JasperDesign  jasperDesign=JRXmlLoader.load("report/configpara.jrxml");
           HashMap para= new HashMap();
          // para.put("ctype",s);
            para.put("cname",s);
           // String sql="select * from item2";
//            JRDesignQuery  newQuery=new JRDesignQuery();
//            //newQuery.setText(sql);
//            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, para,conn);
          //  JasperViewer.viewReport(jasperprint);
              JasperViewer.viewReport(jasperprint, isClosed);
             
//            JasperPrint print = JasperFillManager.fillReport(filename, null, conn);  
//        //JasperPrint print=JasperFillManager.fillReport(filename, para, con);
//        JRViewer viewer=new JRViewer(print);
//        Container c=getContentPane();
//        c.add(viewer);
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    e.printStackTrace();
                    
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
