

import java.awt.Container;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import javax.swing.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JRViewer;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 */
public class Internalitemreport extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalitemreport
     */
    
    Connection conn=null;
   // ConItem cn1;
   mysql2 obj=new mysql2();
        
 
    public Internalitemreport() {
        initComponents();
        conn=obj.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ItemReport");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("PrintaAllItem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PrintCategoryItem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Item_Type");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          try
        {
            //cn1=new ConItem();
                //JasperDesign  jasperDesign=JRXmlLoader.load("report4.jrxml");
           //JasperDesign  jasperDesign=JRXmlLoader.load("Itemreport.jrxml");
            //first report
            // JasperDesign  jasperDesign=JRXmlLoader.load("report/item1.jrxml");
              JasperDesign  jasperDesign=JRXmlLoader.load("report/itemreport.jrxml");
           // String sql="select * from rani";
           // String sql="select  type,item_name,item_type,price,Quantity from item2";
          String  sql= "select  ftype,itemname,itemtype,price from newitem where status ='Áctive'";
            JRDesignQuery  newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, null,conn);
//            JasperViewer.viewReport(jasperprint);
//             JasperViewer.viewReport(jasperprint,false);
            JasperViewer.viewReport(jasperprint, isClosed);
         
         
         
           
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    
                }
                                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
            try
        {
            //cn1=new ConItem();
           // String filename="reportItem.jrxml";
             String filename="itemtype.jrxml";
             String s= jTextField1.getText();
          //  String veg="veg";
             //   JasperDesign  jasperDesign=JRXmlLoader.load("lib/reportItem.jrxml");
             //para report
               //  JasperDesign  jasperDesign=JRXmlLoader.load("itemtype.jrxml");
                 JasperDesign  jasperDesign=JRXmlLoader.load("report/paraitem.jrxml");
           HashMap para= new HashMap();
           para.put("ftype",s);
           // String sql="select * from item2";
//            JRDesignQuery  newQuery=new JRDesignQuery();
//            //newQuery.setText(sql);
//            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, para,conn);
          //  JasperViewer.viewReport(jasperprint);
              JasperViewer.viewReport(jasperprint, isClosed);
             
//            JasperPrint print = JasperFillManager.fillReport(filename, null, conn);  
//        //JasperPrint print=JasperFillManager.fillReport(filename, para, con);
//        JRViewer viewer=new JRViewer(print);
//        Container c=getContentPane();
//        c.add(viewer);
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    e.printStackTrace();
                    
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
            try
        {
            //cn1=new ConItem();
                //JasperDesign  jasperDesign=JRXmlLoader.load("report4.jrxml");
           //JasperDesign  jasperDesign=JRXmlLoader.load("Itemreport.jrxml");
//             JasperDesign  jasperDesign=JRXmlLoader.load("report/item1.jrxml");
//           // String sql="select * from rani";
//             String s1=jTextField2.getText();
//            String sql="select  type,item_name,item_type,price,Quantity from item2 where item_name='"+s1+"'";
//            JRDesignQuery  newQuery=new JRDesignQuery();
//            newQuery.setText(sql);
//            jasperDesign.setQuery(newQuery);
//            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
//            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, null,conn);
////            JasperViewer.viewReport(jasperprint);
////             JasperViewer.viewReport(jasperprint,false);
//            JasperViewer.viewReport(jasperprint, isClosed);
            
            
            //for displaying new item
             JasperDesign  jasperDesign=JRXmlLoader.load("report/itemnamepara.jrxml");
           // String sql="select * from rani";
             String s1=jTextField2.getText();
             String sql="select ftype,itemname,itemtype, price from newitem where status ='Áctive'And itemtype='"+s1+"'";
           // String sql="select  type,item_name,item_type,price,Quantity from item2 where item_name='"+s1+"'";
            JRDesignQuery  newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, null,conn);
//            JasperViewer.viewReport(jasperprint);
//             JasperViewer.viewReport(jasperprint,false);
            JasperViewer.viewReport(jasperprint, isClosed);
         
         
         
           
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    
                }
                        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
