/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 */

//import Other.DB;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;

public class InternalAttendance extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAttendance
     */
    
         int c;
      String s;
      int overtime;
       String overtime2;
       String workingType="";
       int payment;
       int overtime3;
    int   payovertime;
    int tot;
    String dateString ;
     String date1;
    
      String staff_id = null;
    String s_type  = null;
    String date = null;
    String w_type= null;
    String start_time = null;
    String end_time = null;
    String working_hours = null;
//    FileInputStream fin;
 //   File file ;
    String overtimedb = null;
    String leave = null;
    String reason = null;
    String paymentdb = null;
    //String employeeJoiningDate = null;
////    String employeeCompanyCode = GlobalValues.current_company;
////    String employeeCreatedIp = GlobalValues.current_ip;
////    String employeeModifiedIp = GlobalValues.current_ip;
    String selectedId = null;
    ResultSet rs;
    //for stafftable variable
    int table_counter=0;
    
    ArrayList id_array=new ArrayList(0);
            
//    int employeeCreatedStaffcode = GlobalValues.login_emp_id;
   // int employeeModifiedStaffcode = GlobalValues.login_emp_id;

    
  //  JFrame frame = new JFrame();
  ConItem cn1=new ConItem();
  
    DB db = new DB();
    public InternalAttendance() {
        initComponents();
        
         jDateChooser1.setDateFormatString("yyyy-MM-dd");
       jDateChooser2.setDateFormatString("yyyy-MM-dd");
          jDateChooser3.setDateFormatString("yyyy-MM-dd");
           jComboBox3.removeAllItems();
        fillrec();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField13 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stafftable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setTitle("StaffAttendance");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "StaffAttendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel4.setText("Working Type");

        jLabel3.setText("Desination");

        jLabel2.setText("Date");

        jLabel1.setText("Staff_Id");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("d MMM,yyyy");

        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField13FocusGained(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FullTime", "Leave", " " }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox2MouseEntered(evt);
            }
        });
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Button-Add-icon.png")); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Button-Close-icon.png")); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Selected");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Database-Active-icon.png")); // NOI18N
        jButton4.setText("Addindb");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 186, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(180, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        jLabel5.setText("Start_Time");

        jLabel6.setText("End_Time");

        jLabel7.setText("Working_hours");

        jLabel8.setText("OverTime");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel20.setText("Reason");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(47, 47, 47)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jLabel9.setText("Payment");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(366, 366, 366))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Staff_Id");

        jLabel17.setText("Date");

        jLabel18.setText("To");

        stafftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SerialNo", "Date", "Working_Type", "Working_Hours", "Overtime", "Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stafftable);

        jLabel19.setText("TotalPayment");

        jButton5.setText("AddinTable");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("showPayment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 132, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jLabel19)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  void fillrec()
    {
        try
        {
            cn1=new ConItem();
            cn1.st=cn1.con.createStatement();
           // String itemname=t2.getText(); 
            
            cn1.rs=cn1.st.executeQuery("select Staff_Id from staff ");
                        if(cn1.rs.next())
            {do
            {
                jComboBox3.addItem(cn1.rs.getString("Staff_Id")+" ");
                
                            }while(cn1.rs.next());
            }
            else
            {
                System.out.println("no record is added");
                
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
     
      void search()
    {try
    {
        ConItem cn1=new ConItem();
        cn1.st=cn1.con.createStatement();
      //  cn1.stmt=cn1.con.prepareStatement("update item4 set item_name=? where item_no=?");
        //t1.selectAll();
        //t1.setText("");
    //    int ino=Integer.parseInt(t1.getText());
       // String s=(t1.getText());
        String s=String.valueOf(jComboBox3.getSelectedItem());
        cn1.rs=cn1.st.executeQuery("select * from staff where Staff_Id='" +s+"'");
        
        if(cn1.rs.next())
//                
        {
            
          //  t2.setText(String.valueOf(cn1.rs.getInt("item_id")));
//                
//              jTextField2.setText(String.valueOf(cn1.rs.getInt("holidays")));
//                jTextField3.setText(String.valueOf(cn1.rs.getInt("working_hours")));
//                  jTextField4.setText(String.valueOf(cn1.rs.getInt("overtime")));
//                    jTextField9.setText(String.valueOf(cn1.rs.getInt("basic")));
//                     jTextField5.setText(String.valueOf(cn1.rs.getDouble("ha")));
//                                          jTextField6.setText(String.valueOf(cn1.rs.getDouble("da")));
//jTextField7.setText(String.valueOf(cn1.rs.getDouble("esic")));
jTextField13.setText(cn1.rs.getString("designation"));
//jTextField6.setText(String.valueOf(cn1.rs.getDouble("ha")));


//
//                          t3.setText(cn1.rs.getString("type")); 
//                          t4.setText(String.valueOf(cn1.rs.getInt("price")));
//                          t5.setText(String.valueOf(cn1.rs.getInt("Quantity")));
//                          t6.setText(cn1.rs.getString("description"));
                  
                }
        
        else
        {
            System.out.println("no record found");
            
        }
    }catch(Exception e)
    {
        System.out.println(e);
       // e.setStackTrace(stackTrace);
       e.printStackTrace(); 
    } }
       
      
        public void loadInTable(){
        //ConItem cn1=new ConItem();
        
             java.util.Date dateFromDateChooser1 = jDateChooser2.getDate();
           System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
 //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1); 
String dateString1 = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1); 

             java.util.Date dateFromDateChooser2 = jDateChooser3.getDate();
           System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
 //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1); 
String dateString2 = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser2); 
        table_counter=1; //id_array
       String sid=jTextField1.getText();
//       String d1=jTextField7.getText();
//       String d2=jTextField8.getText();
       //  String sql = "select  item_id, item_name,item_type,type,price,Quantity from item2 where type='veg'";
          //String sql = "select  sa_id,date1, w_type,working_hours,overtime,payment from staffattendance ";
          // String sql = "select  sa_id,date1, w_type,working_hours,overtime,payment from staffattendance where staff_id='"+sid+"'And date1 between '"+d1+"' And '"+d2+"'  ORDER BY date1";
           String sql = "select  sa_id,date1, w_type,working_hours,overtime,payment from staffattendance where staff_id='"+sid+"'And date1 between '"+dateString1+"' And '"+dateString2+"'  ORDER BY date1";
            try{
                 ConItem cn1=new ConItem();
               // Connection con = (Connection) Action.getDBConnection();
              cn1. st = cn1. con.createStatement();
                cn1. rs = cn1.st.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) stafftable.getModel();
                model.setRowCount(0);
                Object data[] = new Object[6];
                double total=0, payment;
                while(cn1.rs.next())
                {
                    id_array.add(cn1.rs.getObject("sa_id"));
                    data[0] = table_counter+"";
                    data[1] = cn1.rs.getObject("date1");
                    data[2] =cn1. rs.getObject("w_type");
                    data[3] = cn1.rs.getObject("working_hours");
                  data[4] = cn1.rs.getObject("overtime");
                  payment=cn1.rs.getDouble("payment");
                  data[5] = payment+"";
                    model.addRow(data);
                    total+=payment;
                    table_counter++;
                    
                }
                cn1.rs.close();
                cn1.st.close();
                 jTextField12.setText(total+"");
                 GlobalVariable.gpayment=total;
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
          public static java.util.Date  constructDate(String date1,String time1)
    {
           
            String datearr[]=date1.split("-");
          String date=datearr[0];
              String month=datearr[1];
                String year=datearr[2];
             String timeArr[]=time1.split(":");
           
              System.out.println("date="+date+"month="+month+"year="+year);
              String hr=timeArr[0];
              String min=timeArr[1];
              String ss=timeArr[2];
             
              java.util.Date returndate=new java.util.Date(
                      ((Integer.valueOf(year))-1900),
                  ((Integer.valueOf(month))-1),
                   Integer.valueOf(date),
                     Integer.valueOf(hr),
                      Integer.valueOf(min),
                      Integer.valueOf(ss));
              
              System.out.println("returndate="+returndate);
        
        
        
        return returndate;
    }
    
    public static long calculateDifference(String inTime,String outTime)
    {
        
        long inlong=ConvertTimeTolong(inTime);
        long outTimelong=ConvertTimeTolong(outTime);
        
        
        long diff=outTimelong-inlong;
        return diff;
        
    }
    public static long ConvertTimeTolong(String TimeCal)
    {
        
        String Timearra[]=TimeCal.split(":");
        
        String hr=Timearra[0];
        String mm=Timearra[1];
        String ss=Timearra[2];
        
        long Timecall=(long)((Integer.valueOf(hr))*3600+(Integer.valueOf(mm))*60+(Integer.valueOf(ss)));
        
        System.out.println("Timecall="+Timecall);
        
        return Timecall;
    }
    
    
public int addAttendanceInDB()
{
    System.out.println("addAttendanceInDB start");
    
    
    
    System.out.println("addAttendanceInDB end");
    
    return 0;
}
    
    
public  void performleaveoperation()
{
     String  l=jComboBox2.getSelectedItem().toString();
            java.util.Date dateFromDateChooser1 = jDateChooser1.getDate();
           System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
 //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1); 
dateString = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1); 
    System.out.println("performleaveoperation-dateString="+dateString);
     
         
            staff_id =(jComboBox3.getSelectedItem()).toString();
            System.out.println("jButton4ActionPerformed staff_id="+staff_id);
            s_type=jTextField13.getText();
            
            date= dateString ;
           // start_time = jTextField2.getText();
           // end_time=jTextField3.getText();
           // working_hours=jTextField4.getText();
            //overtimedb=jTextField5.getText();
            reason=jTextField12.getText();
            paymentdb=jTextField6.getText();
    if(l.equals("Leave"))
    {
           jPanel5.setVisible(true);
               jTextField5.setText("0");
            
          if( jTextField15.getText().equals(""))
              {
                   JOptionPane.showMessageDialog(this, "please enter  reason"); 
                    return;
              }
        
        System.out.println("staff_id="+staff_id+"\t s_type="+s_type+"\t date="+date);        
         
                               String sql="Insert into staffattendance(staff_id,s_type,date1,w_type,start_time,end_time,working_hours,overtime,staffattendance.leave,reason,payment) values (?,?,?,?,?,?,?,?,?,?,?)";
                
                    int e = db.insert_data(sql,
                                                                    new String[]{staff_id, s_type,date,
                                                                     l,"0","0","0"
                                                                    ,"0","Yes",reason,"0"});
                    
                    
                    System.out.println("performleaveoperation e="+e);
if(e>0)
{
      JOptionPane.showMessageDialog(this, "data is save"); 
    
}
               
            
}
    
}
        
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusGained
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jTextField13FocusGained

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

        //        System.out.println("jComboBox2MouseClicked start");
        //        String s=String.valueOf(jComboBox2.getSelectedItem());
        //        workingType=s;
        //        System.out.println("workintype="+workingType);
        //
        //        if(s.equals("FullTime"))
        //        {
            //            jPanel2.setVisible(true);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(false);
            //        }
        //        if(s.equals("HalfTime"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(true);
            //            jPanel4.setVisible(false);
            //        }
        //
        //        if(s.equals("Leave"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(true);
            //             jTextField6.setText("0");
            //        }
        //        workingType=(String)jComboBox2.getSelectedItem();
        //        System.out.println("workingtype="+workingType);
        //
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseEntered
        // TODO add your handling code here:
        //        String s=String.valueOf(jComboBox2.getSelectedItem());
        //        workingType=s;
        //        System.out.println("workintype="+workingType);
        //
        //        if(s.equals("FullTime"))
        //        {
            //            jPanel2.setVisible(true);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(false);
            //        }
        //        if(s.equals("HalfTime"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(true);
            //            jPanel4.setVisible(false);
            //        }
        //
        //        if(s.equals("Leave"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(true);
            //             jTextField6.setText("0");
            //        }

    }//GEN-LAST:event_jComboBox2MouseEntered

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        Logger ramiz=Logger.getLogger(Attendance.class.getName());
        ramiz.info("ramiz info is changing");

        System.out.println("jComboBox2ItemStateChanged start");

        String valufffe=(String)jComboBox2.getSelectedItem();
        System.out.println("value"+valufffe);

        //  System.out.println("jComboBox2MouseClicked start");
        //  String s=String.valueOf(jComboBox2.getSelectedItem());
        //workingType=s;
        //System.out.println("workintype="+workingType);

        if( valufffe.equals("FullTime"))
        {
            jPanel2.setVisible(true);
            // jPanel3.setVisible(false);
            //jPanel4.setVisible(false);
            jTextField6.setText("");
            
            jLabel5.setEnabled(true);
jLabel6.setEnabled(true);
jLabel7.setEnabled(true);
jLabel18.setEnabled(true);
jTextField2.setEditable(true);
jTextField3.setEditable(true);
jTextField4.setEditable(true);
jTextField5.setEditable(true);
        }
        //        if( valufffe.equals("HalfTime"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(true);
            //            jPanel4.setVisible(false);
            //             jTextField6.setText("");
            //
            //        }

        if( valufffe.equals("Leave"))
        {
          //  jPanel2.setVisible(false);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(true);
jLabel5.setEnabled(false);
jLabel6.setEnabled(false);
jLabel7.setEnabled(false);
jLabel18.setEnabled(false);
jTextField2.setEditable(false);
jTextField3.setEditable(false);
jTextField4.setEditable(false);
jTextField5.setEditable(false);



            //jPanel5.setVisible(true);
            jTextField6.setText("0");
        }
        //workingType=(String)jComboBox2.getSelectedItem();
        System.out.println("workingtype="+ valufffe);

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(("Leave".equals(workingType)))
        {

            performleaveoperation();

        }
        else{
            try
            {

                java.util.Date dateFromDateChooser1 = jDateChooser1.getDate();
                System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
                //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1);
                dateString = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1);
                //dateString=dateFromDateChooser1;
                DateFormat dff=DateFormat.getDateInstance();
                String converdate=dff.format(dateFromDateChooser1);

                //String timeconv=dateFromDateChooser1.getHours()

                System.out.println("converdate="+converdate);

                System.out.println("dateFromDateChooser1="+dateFromDateChooser1);

                System.out.println("dateString="+dateString);

                date1=dateString;

                System.out.println("date1="+date1);
                String time1=(jTextField2.getText());
                System.out.println("time1="+time1);
                String date2=dateString ;

                System.out.println("date2="+date2);

                String time2=jTextField3.getText();
                System.out.println("time2="+time2);

                long diffenceinTime=calculateDifference(time1, time2);
                System.out.println("diffenceinTime="+diffenceinTime);
                //shortcut sout+tab

                if(diffenceinTime <0)
                {

                    System.out.println("u have entered invalid date");
                    JOptionPane.showMessageDialog(this, " Please enter valid time");
                    jTextField3.setText("");
                    return;

                }

                String format=("dd-mm-yyyy HH:mm:ss");
                SimpleDateFormat  sdf=new SimpleDateFormat(format);

                String spacedd=Integer.toString(32);
                System.out.println("spacedd="+spacedd);

                String inputdate1=date1+"\t"+time1;

                System.out.println("inputdate1="+inputdate1);
                String inputdate2=date2+"\t"+time2;
                System.out.println("inputdate2="+inputdate2);

                java.util.Date inputDateDb1=constructDate(date1, time1);
                System.out.println("inputDateDb="+inputDateDb1);
                java.util.Date inputdatedb2=constructDate(date2, time2);
                System.out.println("inputDateDb="+inputdatedb2);

                //   Time t=new Time(WIDTH, WIDTH, WIDTH)

                long diff=inputdatedb2.getTime()-inputDateDb1.getTime();
                double diffinhours=diff/((double)1000*60*60);

                System.out.println(diffinhours);
                System.out.println("Hours="+(int)diffinhours);
                System.out.println("Minutes="+(diffinhours-(int)diffinhours)*60);

                //        catch(Exception e)
                //        {
                    //            e.printStackTrace();
                    //        }
                //
                jTextField4.setText(String.valueOf((int)diffinhours));

                String s=jTextField4.getText();
                overtime=Integer.parseInt(s);
                if( overtime >6)
                {
                    c= overtime-6 ;
                    System.out.println("overtime"+c);
                    overtime2=String.valueOf(c);

                    jTextField5.setText(overtime2);
                  //  jPanel7.setVisible(false);
                    jLabel20.setEnabled(false);
                    jTextField15.setEditable(false); 
                }

                if(overtime==6)
                {
                    jTextField5.setText("0");
                   // jPanel7.setVisible(false);
 jLabel20.setEnabled(false);
                    jTextField15.setEditable(false); 
                }
                if(overtime<6)
                {
                    jTextField5.setText("0");
                    jPanel7.setVisible(true);
                     jLabel20.setEnabled(true);
                    jTextField15.setEditable(true); 
                    //              if( jTextField12.getText().equals(""))
                    //              {
                        //                  System.out.println("ramiz displaying pane");
                        //                  JOptionPane.showMessageDialog(this, "please enter  reason");
                        //             // jPanel5.setVisible(true);
                        //
                        //              }

                    System.out.println("displaying panel........line 623");

                    // jPanel5.setVisible(true);

                }

                //////           String ch=String.valueOf(jComboBox1.getSelectedItem());
                //////           System.out.println("ch"+ch);
                s=String.valueOf(jComboBox2.getSelectedItem());

                String c=jTextField13.getText();
                if(c.equalsIgnoreCase("Maneger")&& !(s.equals("Leave")))

                {
                    //            pa
                    //            String h=jTextField4.getText();

                    //            int c= 66*Integer.parseInt(h);

                    System.out.println("overtime2="+overtime2);
                    if(overtime2==null)
                    {
                        jTextField5.setText("0");
                        payment=66*overtime;

                    }
                    else
                    {
                        overtime3= Integer.parseInt(overtime2);

                        System.out.println("overtime2="+overtime3);

                        payment=66*overtime;
                        // payovertime=66*overtime3;
                        // tot=payment+payovertime;
                        System.out.println("Total Payment in days="+payment);
                    }
                    jTextField6.setText(String.valueOf(payment));

                }

                if(c.equalsIgnoreCase("cook")&& !(s.equals("Leave")))

                {
                    //            pa
                    //            String h=jTextField4.getText();

                    //            int c= 66*Integer.parseInt(h);

                    System.out.println("overtime2="+overtime2);
                    if(overtime2==null)
                    {
                        jTextField5.setText("0");
                        payment=55*overtime;

                    }
                    else
                    {
                        overtime3= Integer.parseInt(overtime2);

                        System.out.println("overtime2="+overtime3);

                        payment=66*overtime;
                        // payovertime=66*overtime3;
                        // tot=payment+payovertime;
                        System.out.println("Total Payment in days="+payment);
                    }
                    jTextField6.setText(String.valueOf(payment));

                }
                if(c.equalsIgnoreCase("Weater")&& !(s.equals("Leave")))

                {
                    //            pa
                    //            String h=jTextField4.getText();

                    //            int c= 66*Integer.parseInt(h);

                    System.out.println("overtime2="+overtime2);
                    if(overtime2==null)
                    {
                        jTextField5.setText("0");
                        payment=44*overtime;

                    }
                    else
                    {
                        overtime3= Integer.parseInt(overtime2);

                        System.out.println("overtime2="+overtime3);

                        payment=66*overtime;
                        // payovertime=66*overtime3;
                        // tot=payment+payovertime;
                        System.out.println("Total Payment in days="+payment);
                    }
                    jTextField6.setText(String.valueOf(payment));

                }
                if(c.equalsIgnoreCase("Helper")&& !(s.equals("Leave")))

                {
                    //            pa
                    //            String h=jTextField4.getText();

                    //            int c= 66*Integer.parseInt(h);

                    System.out.println("overtime2="+overtime2);
                    if(overtime2==null)
                    {
                        jTextField5.setText("0");
                        payment=38*overtime;

                    }
                    else
                    {
                        overtime3= Integer.parseInt(overtime2);

                        System.out.println("overtime2="+overtime3);

                        payment=66*overtime;
                        // payovertime=66*overtime3;
                        // tot=payment+payovertime;
                        System.out.println("Total Payment in days="+payment);
                    }
                    jTextField6.setText(String.valueOf(payment));

                }

                //         if(c.equals("Maneger")&& !(s.equals("Leave")))
                //
                //        {
                    ////            pa
                    ////            String h=jTextField4.getText();
                    //
                    ////            int c= 66*Integer.parseInt(h);
                    //
                    //            System.out.println("overtime2="+overtime2);
                    //            if(overtime2==null)
                    //            {
                        //                jTextField5.setText("0");
                        //             payment=66*overtime;
                        //
                        //            }
                    //            else
                    //            {
                        //            overtime3= Integer.parseInt(overtime2);
                        //
                        //            System.out.println("overtime2="+overtime3);
                        //
                        //            payment=66*overtime;
                        //           // payovertime=66*overtime3;
                        //           // tot=payment+payovertime;
                        //            System.out.println("Total Payment in days="+payment);
                        //            }
                    //            jTextField6.setText(String.valueOf(payment));
                    //
                    //        }
            } catch(Exception e)
            {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //         String s=String.valueOf(jComboBox2.getSelectedItem());
        //        if(s.equals("FullTime"))
        //        {
            //            jPanel2.setVisible(true);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(false);
            //        }
        //        if(s.equals("HalfTime"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(true);
            //            jPanel4.setVisible(false);
            //        }
        //
        //        if(s.equals("Leave"))
        //        {
            //            jPanel2.setVisible(false);
            //            jPanel3.setVisible(false);
            //            jPanel4.setVisible(true);
            //            jTextField6.setText("0");
            //        }
        //
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        { System.out.println("jButton4ActionPerformed");

            w_type=jComboBox2.getSelectedItem().toString();
            System.out.println("jButton4ActionPerformed wtype="+w_type);

            if(w_type.equals("Leave"))
            {
                performleaveoperation();
                return;

            }

            staff_id =(jComboBox3.getSelectedItem()).toString();
            System.out.println("jButton4ActionPerformed staff_id="+staff_id);
            s_type=jTextField13.getText();

            date=date1;
            start_time = jTextField2.getText();
            end_time=jTextField3.getText();
            working_hours=jTextField4.getText();
            overtimedb=jTextField5.getText();
            reason=jTextField15.getText();
            paymentdb=jTextField6.getText();

            System.out.println("jButton4ActionPerformed paymentdb="+paymentdb);
            System.out.println("jButton4ActionPerformed working_hours="+working_hours);

            System.out.println("jButton4ActionPerformed reason="+reason);

            int workinghrsint=0;
            if(working_hours!=null)
            {
                workinghrsint=Integer.valueOf(working_hours);

            }

            if(workinghrsint <6)
            {

                jPanel5.setVisible(true);
                System.out.println("working hrs less than 6");

                if(reason==null || reason.length()==0)
                {
                    JOptionPane.showMessageDialog(this,"Please enter reason for working less than 6 hours"
                        + "");
                    return;

                }
                //jPanel5.setVisible(true);

            }

            int flagValidation = 0;
            String validation = null;

            if(start_time.equals(""))
            {
                validation = "\nPlease Enter valid time ";
                flagValidation = 1;
            }

            if(end_time.equals(""))
            {
                validation = validation + "\nPlease Enter  valid time";
                flagValidation = 1;
            }

            else if(!(w_type.equals("Leave")))
            {
                //    //check for start_tiem,end_time

                if(flagValidation == 1)

                {
                    JOptionPane.showMessageDialog(null,validation,"Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String sql="Insert into staffattendance(staff_id,s_type,date1,w_type,start_time,end_time,working_hours,overtime,staffattendance.leave,reason,payment) values (?,?,?,?,?,?,?,?,?,?,?)";

                int e = db.insert_data(sql,
                    new String[]{staff_id, s_type,date,
                        w_type,start_time,end_time,working_hours
                        ,overtimedb,"N",reason,paymentdb});
                //staff_id1,s_type2,date3,w_type4,start_time5,end_time6,working_hours7,employee_overtime8,leave9,reason10,payment11
                //01

            }
            else
            {
                //else block for adding data for

                String sql="Insert into staffattendance(staff_id,s_type,date1,w_type,start_time,end_time,working_hours,overtime,staffattendance.leave,reason,payment) values (?,?,?,?,?,?,?,?,?,?,?)";

                int e = db.insert_data(sql,
                    new String[]{staff_id, s_type,date,
                        w_type,"0","0","0"
                        ,"0","Yes",reason,paymentdb});

            }

        }  catch(Exception e)
        {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "record inserted");

        //              JOptionPane.showMessageDialog(null, "Data Saved","Error",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loadInTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Payment p=new Payment();
        p.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable stafftable;
    // End of variables declaration//GEN-END:variables
}
