
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 */
public class staffReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReport
     */
    
      Connection conn=null;
   // ConItem cn1;
   mysql2 obj=new mysql2();
        
 
    
        //conn=obj.connect();
    public staffReport() {
        initComponents();
          conn=obj.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);

        jButton1.setText("View All Staff");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ViewParticularStaff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
            //cn1=new ConItem();
                //JasperDesign  jasperDesign=JRXmlLoader.load("report4.jrxml");
          // JasperDesign  jasperDesign=JRXmlLoader.load("Finals.jrxml");
            //new staff display
              JasperDesign  jasperDesign=JRXmlLoader.load("report/staff3.jrxml");
           // String sql="select * from rani";
        //    String sql="SELECT name,address ,phone_1,designation from staff";
         String sql=   "SELECT name,designation,address,phone_1 FROM staff WHERE status = 'Active'";
            JRDesignQuery  newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, null,conn);
            //JasperViewer.viewReport(jasperprint);
           
            JasperViewer.viewReport(jasperprint, isClosed);
            
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    
                }
                                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try
        {
            //cn1=new ConItem();
           // String filename="reportItem.jrxml";
             String filename="itemtype.jrxml";
             String s= jTextField1.getText();
          //  String veg="veg";
             //   JasperDesign  jasperDesign=JRXmlLoader.load("lib/reportItem.jrxml");
                 //JasperDesign  jasperDesign=JRXmlLoader.load("staffpara.jrxml");
                 //fatima staff report display
                 JasperDesign  jasperDesign=JRXmlLoader.load("satffpara.jrxml");
           HashMap para= new HashMap();
           //para.put("sname",s);
           para.put("name",s);
           
           // String sql="select * from item2";
//            JRDesignQuery  newQuery=new JRDesignQuery();
//            //newQuery.setText(sql);
//            jasperDesign.setQuery(newQuery);
            JasperReport jasperreport=JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperprint=JasperFillManager.fillReport(jasperreport, para,conn);
          //  JasperViewer.viewReport(jasperprint);
              JasperViewer.viewReport(jasperprint, isClosed);
             
//            JasperPrint print = JasperFillManager.fillReport(filename, null, conn);  
//        //JasperPrint print=JasperFillManager.fillReport(filename, para, con);
//        JRViewer viewer=new JRViewer(print);
//        Container c=getContentPane();
//        c.add(viewer);
            
        }catch(Exception e)
                {
                   // JOptionPane.showMessageDialoge(null,e);
                    JOptionPane.showMessageDialog(null, e);   
                    e.printStackTrace();
                    
                }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
