
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.exolab.castor.types.Date;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 */
public class staffedit extends javax.swing.JFrame {

    /**
     * Creates new form staffedit
     */
    
    
      String id;
      TableRowSorter<TableModel> sorter;
     ArrayList id_array=new ArrayList(0);
    ArrayList<String> getrow1=new ArrayList<String>();
    int table_counter=0;    
    TableModel model;
    String searchtext;
    DefaultTableModel dataModel;
     DB db=new DB ();
    public staffedit() {
        initComponents();
         loadInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        config = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        st2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        st3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        st4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        st5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        st6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        config.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SerialNo", "Name", "Address", "phone1", "phone2", "designation", "date_of_Birth", "date_of_joining"
            }
        ));
        config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(config);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Phone1");

        jLabel5.setText("Phone2");

        st5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Designation");

        jLabel9.setText("Date_of_Birth");

        jLabel10.setText("Date_of_joining");

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Actions-document-save-icon.png")); // NOI18N
        jButton1.setText("Save/Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Pencil-icon.png")); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Misc-Delete-Database-icon.png")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Search-icon.png")); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Button-Close-icon.png")); // NOI18N
        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("F:\\ButtonImage\\Actions-edit-clear-icon.png")); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton6))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(st2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(st4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(st5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(st6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void loadInTable(){
        //ConItem cn1=new ConItem();
        table_counter=1; //id_array
       
       //  String sql = "select  item_id, item_name,item_type,type,price,Quantity from item2 where type='veg'";
          String sql = "select Staff_Id,  name, address,phone_1,phone_2,designation,dob,doj from staff ";
            try{
                 ConItem cn1=new ConItem();
               // Connection con = (Connection) Action.getDBConnection();
              cn1. st = cn1. con.createStatement();
                cn1. rs = cn1.st.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) config.getModel();
                model.setRowCount(0);
                Object data[] = new Object[8];
                while(cn1.rs.next())
                {
                    id_array.add(cn1.rs.getObject("Staff_Id"));
                    data[0] = table_counter+"";
                    data[1] = cn1.rs.getObject("name");
                    data[2] =cn1. rs.getObject("address");
                    data[3] = cn1.rs.getObject("phone_1");
                  data[4] = cn1.rs.getObject("phone_2");
                  data[5] = cn1.rs.getObject("designation");
                  data[6] = cn1.rs.getObject("dob");
                  data[7] = cn1.rs.getObject("doj");
                  
                    model.addRow(data);
                    table_counter++;     
                }
                cn1.rs.close();
                cn1.st.close();
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
//       void update()
//    {
//        try
//           
//        {   ConItem cn1=new ConItem();
//            cn1.st=cn1.con.createStatement();
//            
//            //int ino=Integer.parseInt(t1.getText());
//            String s=(st2.getText());
//            
//         cn1.stmt=cn1.con.prepareStatement("update Staff set name=?,address=? ,phone_1=?,phone_2=?,designation=?,dob=?,doj=?where name='"+s+"'");
//            //cn1.stmt.setInt(1, Integer.parseInt(t1.getText()));
//          
//           cn1.stmt.setString(1,(st2.getText()));
//             cn1.stmt.setString(2,(st3.getText()));
//              cn1.stmt.setInt(3,Integer.parseInt(st4.getText()));
//               cn1.stmt.setInt(4,Integer.parseInt(st5.getText()));
//                 cn1.stmt.setDate(5,(st6.getText()));
//                   cn1.stmt.setDouble(6,Double.parseDouble(jTextField1.getText()));
//                  // cn1.stmt.setDouble(7,Double.parseDouble(jTextField8.getText()));
//                   
////          cn1.stmt.setString(2,t3.getText());
////         String p=(t4.getText());
////        // String  p2= new Integer(p).toString();
////         
////          cn1.stmt.setInt(3,Integer.parseInt(p));
////           String p2=(t5.getText());
////            cn1.stmt.setInt(4,Integer.parseInt(p2));
////          cn1.stmt.setString(5,t6.getText());
//         // cn1.stmt.setInt(4,t5.getText().toString());
//            //cn1.stmt.setString(5,t5.getText());       
//           // p2 = (p);
//   
//            int i=cn1.stmt.executeUpdate();
//            
//            if(i==-1)
//            {
//                System.out.println("no record is updated" );
//                 JOptionPane.showMessageDialog(this, "record not updated"); 
//                 
//                
//            }
//            else
//            {
//                System.out.println("record is updated");
//                 JOptionPane.showMessageDialog(this, "record  updated"); 
//            }
//        }catch(Exception e)
//                {
//                   System.out.println(e);
//                 e.printStackTrace();  
//                }
//        //loadInTable();
//    }
      
        void update() {
  String name,add,ph1,ph2,desi,dob,doj;
  name=st2.getText();
  add=st3.getText();
  ph1=st4.getText();
   ph2=st5.getText();
  desi=st6.getText();
  dob=jTextField1.getText();
  doj=jTextField2.getText();
  try
  {
  db.update_data("update Staff set name=?,address=?,phone_1=?,phone_2=?,designation=?,dob=?,doj=? where Staff_Id="+id+"",new String[]{name,add,ph1,ph2,desi, dob, doj});
  JOptionPane.showMessageDialog(this, "Updated successfully..");
  }//'"+s+"'
  catch(Exception e)
  {}
  //'"+name+"'
  
   /* String str="update expenses set description='"+txtexpname.getText()+"',amount='"+txtamount.getText()+"',date='"+jDateChooser.getDate()+"' where description='"+txtexpname.getText()+"'";
					//System.out.println(str);
					int u=st.executeUpdate(str);
					//int u=st.executeUpdate("update medicine set'"+inputText[3].getText()+"','"+inputText[4].getText()+"','"+inputText[5].getText()+"','"+inputText[6].getText()+"' where '"+inputText[1].getText()+"' and '"+ch.getSelectedItem()+"' and '"+inputText[7].getText()+"'");
					
					
					
                                        * 
					if(u>0)
					  {
					 JOptionPane.showMessageDialog(null,"Record is updated  succsefully","update expenses",JOptionPane.INFORMATION_MESSAGE);
					   
			dispose();		 }*/
			    	
    }
			   
     
        void delete()
    {  try
    {
         ConItem cn1=new ConItem();
         //int ino=Integer.parseInt(st1.getText());
         String s=st2.getText();
         cn1.st=cn1.con.createStatement();
        cn1.stmt=cn1.con.prepareStatement("delete  from Staff where name=?");
       cn1.stmt.setString(1, s);
        int i=cn1.stmt.executeUpdate();
        if(i==-1)
        {
            System.out.println("not deleted");
             JOptionPane.showMessageDialog(this, "record is not deleted"); 
            
        }
        else
        {
            System.out.println("record is deleted");
             JOptionPane.showMessageDialog(this, "record is deleted"); 
        }
    
    }catch(Exception e)
    {
        System.out.println(e);
        e.printStackTrace();
        
    }
    }   
    private void configMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseClicked
        // TODO add your handling code here:
        try
        {int sr=config.getSelectedRow();
            // String id=getrow.add(sr).toString();

            //select * from item  where item_id=
          //  String id;
//            id=id_array.get(sr).toString();
//            ConItem cn1=new ConItem();
//            cn1.st=cn1.con.createStatement();
//            cn1.rs=cn1.st.executeQuery("Select * from config where c_id="+id);
//
//            if(cn1.rs.next())
//            {
//                
                
                
                  id=id_array.get(sr).toString();
    ConItem cn1=new ConItem();
    cn1.st=cn1.con.createStatement();
    cn1.rs=cn1.st.executeQuery("Select * from staff where Staff_Id="+id);
    
    if(cn1.rs.next())
    {
        st2.setText(cn1.rs.getString("name"));
           st3.setText(String.valueOf(cn1.rs.getString("address")));
             st4.setText(String.valueOf(cn1.rs.getInt("phone_1")));
              st5.setText(String.valueOf(cn1.rs.getInt("phone_2")));
                 st6.setText(String.valueOf(cn1.rs.getString("designation")));
               jTextField1.setText(String.valueOf(cn1.rs.getDate("dob")));
          jTextField2.setText(String.valueOf(cn1.rs.getDate("doj")));
    }
    
        
            

        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_configMouseClicked

    private void st5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // add();
//        try
//        {
//
//            java.util.Date dateFromDateChooser1 = dt1.getDate();
//            System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
//            //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1);
//            dateString = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1);
//
//            java.util.Date dateFromDateChooser = dt2.getDate();
//            System.out.println("dateFromDateChooser1="+dateFromDateChooser1);
//            //dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser1);
//            dateString2 = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser);
//
//            name = st2.getText();
//            address  =st3.getText() ;
//            phone1 = st4.getText();
//            phone2=st5.getText();
//            designation= st6.getText();
//            dob = dateString;
//            doj = dateString2;
//            // String pf = null;
//
//            int flagValidation = 0;
//            String validation = null;
//
//            if(name.equals(""))
//            {
//                validation = "\nPlease Enter valid name ";
//                flagValidation = 1;
//            }
//
//            if(address.equals(""))
//            {
//                validation = validation + "\nPlease Enter  valid time";
//                flagValidation = 1;
//            }
//
//            if(flagValidation == 1)
//
//            {
//                JOptionPane.showMessageDialog(null,validation,"Error",JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//
//            else
//            {
//                String sql="Insert into Staff(name,address,phone_1,phone_2,designation,dob,doj) values (?,?,?,?,?,?,?)";
//
//                int e = db.insert_data(sql,
//                    new String[]{name, address,phone1,
//                        phone2,designation,dob,doj
//                    });
//
//                    JOptionPane.showMessageDialog(this, "record inserted");
//
//                }
//
//            }  catch(Exception e)
//            {
//                e.printStackTrace();
//            }
//            //   JOptionPane.showMessageDialog(this, "record inserted");

            //              JOptionPane.showMessageDialog(null, "Data Saved","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //update();
        update();
         loadInTable();
        //loadInTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        delete();
           loadInTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //search();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        st2.setText("");
        st3.setText("");
        st4.setText("");
        st5.setText("");
        st6.setText("");
        jTextField1.setText("");
         jTextField2.setText("");
        
       //st2.setText("");
       // dt1.cleanup();
        //dt2.cleanup();
      //  dt1.setDateFormatString("");
        //dt2.setDateFormatString("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
         String date = new DatePicker(new JFrame()).setPickedDate();
        jTextField1.setText(date);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
         String date = new DatePicker(new JFrame()).setPickedDate();
        jTextField2.setText(date);
    }//GEN-LAST:event_jTextField2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffedit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable config;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField st2;
    private javax.swing.JTextField st3;
    private javax.swing.JTextField st4;
    private javax.swing.JTextField st5;
    private javax.swing.JTextField st6;
    // End of variables declaration//GEN-END:variables
}
