
import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiz
 */
public class viewsupplier extends javax.swing.JDialog {

    /**
     * Creates new form viewsupplier
     */
     String id;
    
    ArrayList id_array=new ArrayList(0);
    ArrayList<String> getrow1=new ArrayList<String>();
    int table_counter=0;  
    DB db=new DB();
    
    public viewsupplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadInTable();
    }

    public void loadInTable(){
        //ConItem cn1=new ConItem();
    
        table_counter=1; //id_array
       
       //  String sql = "select  item_id, item_name,item_type,type,price,Quantity from item2 where type='veg'";
          //String sql = "select  Item_id, item_name,item_type,type,price,Quantity from item2 ";
           // String sql = "select  Item_id, itemname,itemtype,ftype,price,quantity from newitem where status='Active' ";
              String sql = "select  supplier_id, supplier_name,address,city,state,email_id,mobile_no from supplier where status='Active' ";
            try{
                 ConItem cn1=new ConItem();
               // Connection con = (Connection) Action.getDBConnection();
              cn1. st = cn1. con.createStatement();
                cn1. rs = cn1.st.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) item1.getModel();
                model.setRowCount(0);
                Object data[] = new Object[7];
                while(cn1.rs.next())
                {
                    id_array.add(cn1.rs.getObject("supplier_id"));
                    data[0] = table_counter+"";
                    data[1] = cn1.rs.getObject("supplier_name");
                    data[2] =cn1. rs.getObject("address");
                    data[3] = cn1.rs.getObject("city");
                       data[4] = cn1.rs.getObject("state");
                  data[5] = cn1.rs.getObject("email_id");
                  data[6] = cn1.rs.getObject("mobile_no");
                    model.addRow(data);
                    table_counter++;     
                }
                cn1.rs.close();
                cn1.st.close();
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        item1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        item1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        item1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Supplier_Name", "Address", "City", "State", "Email_id", "Mobile_No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(item1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
//        try
//        {int sr=item1.getSelectedRow();
//            // String id=getrow.add(sr).toString();
//
//            //select * from item  where item_id=
//            //  String id;
//            //            id=id_array.get(sr).toString();
//            //            ConItem cn1=new ConItem();
//            //            cn1.st=cn1.con.createStatement();
//            //            cn1.rs=cn1.st.executeQuery("Select * from config where c_id="+id);
//            //
//            //            if(cn1.rs.next())
//            //            {
//                //
//
//                id=id_array.get(sr).toString();
//                ConItem cn1=new ConItem();
//                cn1.st=cn1.con.createStatement();
//                //cn1.rs=cn1.st.executeQuery("Select * from staff where Staff_Id="+id);
//                cn1.rs=cn1.st.executeQuery("Select * from supplier  where supplier_id="+id);
//                if(cn1.rs.next())
//                {
//                    jTextField1.setText(cn1.rs.getString("supplier_name"));
//                    jTextField2.setText((cn1.rs.getString("address")));
//                    jTextField3.setText((cn1.rs.getString("city")));
//                    jTextField4.setText((cn1.rs.getString("state")));
//                    jTextField5.setText((cn1.rs.getString("email_id")));
//                    jTextField6.setText(String.valueOf(cn1.rs.getInt("mobile_no")));
//                    //               jTextField1.setText(String.valueOf(cn1.rs.getDate("dob")));
//                    //          jTextField2.setText(String.valueOf(cn1.rs.getDate("doj")));
//                }
//
//            }catch(Exception e)
//            {
//                e.printStackTrace();
//            }
    }//GEN-LAST:event_item1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try
                  {
                     UIManager.setLookAndFeel(new SyntheticaBlueMoonLookAndFeel());
                  }
                         catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                
                viewsupplier dialog = new viewsupplier(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable item1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
